dd
edson-pro/gym-kmarketer pull request #1
Opened 2022-09-19 07:14 UTC by edson-pro

2022-09-19 07:26 UTC, hirwaaldo1 requested changes

2022-09-19 07:26 UTC, hirwaaldo1 commented on main.css
> +}
change this element name

2022-09-19 08:10 UTC, hirwaaldo1 approved these changes
👌

2022-09-19 08:32 UTC, rithaven approved these changes
Well done keep it Up

2022-09-19 23:31 UTC, Morrism1 requested changes
Resolve these issues. Most of them are concerning where you are referencing a BLOCK that not exist yet.

2022-09-19 23:31 UTC, Morrism1 commented on index.html
> +        <div class="whycard__item">
Here we have `whycard__item` which I can read as we have a BLOCK called `whycard` and ELEMENT `item` but we don't have a BLOCK with such name.

2022-09-19 23:31 UTC, Morrism1 commented on index.html
> +        <div class="whycard__item">
Also this applies to all children elements referencing a BLOCK that we don't have.

2022-09-19 23:31 UTC, Morrism1 commented on index.html
> +        <div class="testimony__item">
Here also you are referencing a BLOCK `testimony` which we don't have.

2022-09-19 23:31 UTC, Morrism1 commented on index.html
> +          <p class="testimony__message">
Here also you are referencing a BLOCK `testimony` which we don't have.

2022-09-19 23:31 UTC, Morrism1 commented on index.html
> +        <div class="testimony__item">
Here also you are referencing a BLOCK `testimony` which we don't have.

2022-09-19 23:31 UTC, Morrism1 commented on index.html
> +          <p class="testimony__message">
Here also you are referencing a BLOCK `testimony` which we don't have.

2022-09-19 23:31 UTC, Morrism1 commented on index.html
> +          <div class="testimonyuser__item">
Here also you are referencing a BLOCK `testimonyuser` which we don't have.

2022-09-19 23:31 UTC, Morrism1 commented on index.html
> +            <div>
Using elements that don't have classes is not necessary.

2022-09-20 09:14 UTC, rithaven commented
Cordially noted!






*0787412101/0726882125*
***@***.*** ***@***.***>
Computer Engineer/ from UR-Collage of science and Technology
Full stack web developer/From wecode (Moringa school)




On Tue, Sep 20, 2022 at 1:32 AM Maurice Murangwa ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Resolve these issues. Most of them are concerning where you are
> referencing a BLOCK that not exist yet.
> ------------------------------
>
> In index.html
> <https://github.com/edson-pro/gym-kmarketer/pull/1#discussion_r974761487>:
>
> > +      </p>
> +      <div class="hero__links">
> +        <a class="btn btn--secondary" href="">Get Quote Now</a>
> +        <a class="btn btn--outlined" href="">Learn More</a>
> +      </div>
> +    </div>
> +    <div class="why">
> +      <div class="why__header">
> +        <h4 class="why__title">Why choose us</h4>
> +        <p class="why__subtitle">
> +          Problems trying to resolve the conflict between the two major realms
> +          of Classical physics: Newtonian mechanics
> +        </p>
> +      </div>
> +      <div class="why__content">
> +        <div class="whycard__item">
>
> Here we have whycard__item which I can read as we have a BLOCK called
> whycard and ELEMENT item but we don't have a BLOCK with such name.
> ------------------------------
>
> In index.html
> <https://github.com/edson-pro/gym-kmarketer/pull/1#discussion_r974762822>:
>
> > +
> +        <img src="/images/cover.jpg" class="features__cover" alt="" />
> +      </div>
> +      <div class="features__bg" />
> +    </div>
> +
> +    <div class="testimonies">
> +      <div class="testimonies__header">
> +        <h4 class="testimonies__title">What Clients Say</h4>
> +        <p class="testimonies__subtitle">
> +          Problems trying to resolve the conflict between the two major realms
> +          of Classical physics: Newtonian mechanics
> +        </p>
> +      </div>
> +      <div class="testimonies__content">
> +        <div class="testimony__item">
>
> Here also you are referencing a BLOCK testimony which we don't have.
> ------------------------------
>
> In index.html
> <https://github.com/edson-pro/gym-kmarketer/pull/1#discussion_r974763012>:
>
> > +                d="M94.5324 13.1308L93.1657 19.0488C93.1234 19.228 93.1361 19.4158 93.2021 19.5877C93.2682 19.7596 93.3846 19.9075 93.536 20.0122C93.6875 20.1169 93.867 20.1735 94.0511 20.1746C94.2353 20.1757 94.4154 20.1212 94.5681 20.0183L99.5625 16.6888L104.557 20.0183C104.713 20.1221 104.897 20.1755 105.085 20.1714C105.272 20.1673 105.454 20.1058 105.606 19.9953C105.757 19.8849 105.871 19.7306 105.932 19.5534C105.994 19.3761 105.999 19.1844 105.948 19.0039L104.271 13.1336L108.431 9.38944C108.564 9.26946 108.66 9.11304 108.705 8.93955C108.75 8.76605 108.744 8.58308 108.686 8.41327C108.629 8.24345 108.522 8.09424 108.381 7.98408C108.239 7.87392 108.069 7.80764 107.89 7.79345L102.661 7.37703L100.398 2.36801C100.326 2.20672 100.209 2.06976 100.06 1.97366C99.9121 1.87755 99.7392 1.82642 99.5625 1.82642C99.3858 1.82642 99.2129 1.87755 99.0646 1.97366C98.9163 2.06976 98.799 2.20672 98.7269 2.36801L96.4641 7.37703L91.2349 7.79254C91.0592 7.80645 90.8913 7.87069 90.7511 7.97757C90.611 8.08445 90.5046 8.22943 90.4447 8.39518C90.3848 8.56094 90.3739 8.74044 90.4134 8.91221C90.4528 9.08398 90.5409 9.24074 90.6671 9.36376L94.5324 13.1308ZM97.1492 9.16288C97.313 9.14998 97.4702 9.09328 97.6045 8.99871C97.7387 8.90414 97.8451 8.77519 97.9124 8.62538L99.5625 4.97387L101.213 8.62538C101.28 8.77519 101.386 8.90414 101.52 8.99871C101.655 9.09328 101.812 9.14998 101.976 9.16288L105.619 9.45181L102.619 12.1521C102.358 12.387 102.255 12.7484 102.35 13.0859L103.499 17.108L100.072 14.8231C99.922 14.7222 99.745 14.6683 99.5638 14.6683C99.3827 14.6683 99.2057 14.7222 99.0552 14.8231L95.4744 17.2107L96.4375 13.0409C96.4728 12.8876 96.468 12.7277 96.4237 12.5767C96.3794 12.4257 96.2969 12.2887 96.1843 12.1787L93.3977 9.4619L97.1492 9.16288Z"
> +                fill="#F3CD03"
> +              />
> +            </g>
> +            <defs>
> +              <clipPath id="clip0_964_6448">
> +                <rect
> +                  width="110.068"
> +                  height="22"
> +                  fill="white"
> +                  transform="translate(0.5)"
> +                />
> +              </clipPath>
> +            </defs>
> +          </svg>
> +          <p class="testimony__message">
>
> Here also you are referencing a BLOCK testimony which we don't have.
> ------------------------------
>
> In index.html
> <https://github.com/edson-pro/gym-kmarketer/pull/1#discussion_r974763149>:
>
> > +            Slate helps you see how many more days you need to work to reach
> +            your financial goal.
> +          </p>
> +          <div class="testimonyuser__item">
> +            <img
> +              class="testimonyuser__img"
> +              src="https://avatars.githubusercontent.com/u/78101497?v=4"
> +              alt=""
> +            />
> +            <div>
> +              <h4 class="testimonyuser__user">Regina Miles</h4>
> +              <span class="testimonyuser__role">Designer</span>
> +            </div>
> +          </div>
> +        </div>
> +        <div class="testimony__item">
>
> Here also you are referencing a BLOCK testimony which we don't have.
> ------------------------------
>
> In index.html
> <https://github.com/edson-pro/gym-kmarketer/pull/1#discussion_r974763409>:
>
> > +                d="M94.5324 13.1308L93.1657 19.0488C93.1234 19.228 93.1361 19.4158 93.2021 19.5877C93.2682 19.7596 93.3846 19.9075 93.536 20.0122C93.6875 20.1169 93.867 20.1735 94.0511 20.1746C94.2353 20.1757 94.4154 20.1212 94.5681 20.0183L99.5625 16.6888L104.557 20.0183C104.713 20.1221 104.897 20.1755 105.085 20.1714C105.272 20.1673 105.454 20.1058 105.606 19.9953C105.757 19.8849 105.871 19.7306 105.932 19.5534C105.994 19.3761 105.999 19.1844 105.948 19.0039L104.271 13.1336L108.431 9.38944C108.564 9.26946 108.66 9.11304 108.705 8.93955C108.75 8.76605 108.744 8.58308 108.686 8.41327C108.629 8.24345 108.522 8.09424 108.381 7.98408C108.239 7.87392 108.069 7.80764 107.89 7.79345L102.661 7.37703L100.398 2.36801C100.326 2.20672 100.209 2.06976 100.06 1.97366C99.9121 1.87755 99.7392 1.82642 99.5625 1.82642C99.3858 1.82642 99.2129 1.87755 99.0646 1.97366C98.9163 2.06976 98.799 2.20672 98.7269 2.36801L96.4641 7.37703L91.2349 7.79254C91.0592 7.80645 90.8913 7.87069 90.7511 7.97757C90.611 8.08445 90.5046 8.22943 90.4447 8.39518C90.3848 8.56094 90.3739 8.74044 90.4134 8.91221C90.4528 9.08398 90.5409 9.24074 90.6671 9.36376L94.5324 13.1308ZM97.1492 9.16288C97.313 9.14998 97.4702 9.09328 97.6045 8.99871C97.7387 8.90414 97.8451 8.77519 97.9124 8.62538L99.5625 4.97387L101.213 8.62538C101.28 8.77519 101.386 8.90414 101.52 8.99871C101.655 9.09328 101.812 9.14998 101.976 9.16288L105.619 9.45181L102.619 12.1521C102.358 12.387 102.255 12.7484 102.35 13.0859L103.499 17.108L100.072 14.8231C99.922 14.7222 99.745 14.6683 99.5638 14.6683C99.3827 14.6683 99.2057 14.7222 99.0552 14.8231L95.4744 17.2107L96.4375 13.0409C96.4728 12.8876 96.468 12.7277 96.4237 12.5767C96.3794 12.4257 96.2969 12.2887 96.1843 12.1787L93.3977 9.4619L97.1492 9.16288Z"
> +                fill="#F3CD03"
> +              />
> +            </g>
> +            <defs>
> +              <clipPath id="clip0_964_6448">
> +                <rect
> +                  width="110.068"
> +                  height="22"
> +                  fill="white"
> +                  transform="translate(0.5)"
> +                />
> +              </clipPath>
> +            </defs>
> +          </svg>
> +          <p class="testimony__message">
>
> Here also you are referencing a BLOCK testimony which we don't have.
> ------------------------------
>
> In index.html
> <https://github.com/edson-pro/gym-kmarketer/pull/1#discussion_r974763493>:
>
> > +            <defs>
> +              <clipPath id="clip0_964_6448">
> +                <rect
> +                   [...]

2022-09-21 13:08 UTC, hirwaaldo1 approved these changes

2022-09-21 13:22 UTC, Morrism1 approved these changes
Good Job @edson-pro!

2022-09-21 13:40 UTC, merged